implemented add command

diff --git a/nav b/nav
--- a/nav
+++ b/nav
@@ -90,8 +90,39 @@ function nav_to() {
 }
 
 function nav_add() {
-  echo "not implemented"
-  exit 1
+  local -r shortcut="$1"
+  local -r directory="$2"
+  if [[ -z "$shortcut" ]] || [ -z "$directory" ]; then
+    echo "Please provide a shortcut and a directory."
+    print_help_add
+    exit 1
+  fi
+
+  local -r src="$(realpath "$directory")"
+  if [[ $? -ne 0 ]]; then
+    echo "Error: could not resolve the absolute path for $directory."
+    exit 1
+  fi
+  if [[ ! -d "$src" ]]; then
+    echo "Error: $directory is not a directory."
+    exit 1
+  fi
+
+  local -r dst="$NAV_PATH/$shortcut"
+  if [[ -e "$shortcut" ]]; then
+    echo "Error: $shortcut already exists."
+    exit 1
+  fi
+
+  mkdir -p "$NAV_PATH" &>/dev/null
+
+  ln -s "$src" "$dst"
+  local -r rv="$?"
+  if [[ $rv -ne 0 ]]; then
+    echo "Error: unable to add a shortcut from $shortcut to $directory."
+    exit 1
+  fi
+  echo "Added a shortcut from $shortcut to $src!"
 }
 
 function main() {
